<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Technical Assistance Support Log</title>

<style>
@page {
    size: A4 landscape;
    margin: 15mm 10mm;
}

body {
    font-family: Arial, sans-serif;
    font-size: 12px;
    margin: 0;
}

.a4page {
    width: 100%;
    padding: 0;
    box-sizing: border-box;
}

/* TABLE */
table {
    width: 100%;
    border-collapse: collapse;
    page-break-inside: auto;
}

thead {
    display: table-header-group; /* Repeat header on each page */
}

tfoot {
    display: table-footer-group;
}

th, td {
    border: 1px solid #000;
    padding: 4px;
    text-align: center;
    vertical-align: middle;
}

th {
    background-color: #f5f5f5;
}

tr {
    page-break-inside: avoid; /* Avoid breaking rows */
}
</style>
</head>
<body>

<?php
// === HEADER FOR MPDF ===
$headerHTML = '
<table width="100%">
<tr>
    <td width="15%"><img src="' . base_url('assets/img/cvmc_logo.png', true) . '" height="60"></td>
    <td width="70%" style="text-align:center;">
        Republic of the Philippines<br>
        <strong>DEPARTMENT OF HEALTH</strong><br>
        <strong>CAGAYAN VALLEY MEDICAL CENTER</strong><br>
        Regional Tertiary, Teaching, Training, and Research Medical Center
    </td>
    <td width="15%"><img src="' . base_url('assets/img/DOH_Logo.png', true) . '" height="60"></td>
</tr>
<tr>
    <td colspan="3" style="text-align:right;">
        <b>IM-019-0</b><br>
        <small>28March2025</small>
    </td>
</tr>
<tr>
    <td colspan="3" style="text-align:center;"><h3>Technical Assistance Support Log</h3></td>
</tr>
</table>
<hr>
';
echo $headerHTML;
?>

<!-- TABLE -->
<table>
    <thead>
        <tr>
            <th>Date and Time</th>
            <th>Requested by</th>
            <th>ID No.</th>
            <th>Section/Unit</th>
            <th>Description</th>
            <th>Action Taken</th>
            <th>Status</th>
            <th>Processed by</th>
        </tr>
    </thead>
    <tbody>
    <?php if (!empty($records)): ?>
        <?php foreach ($records as $row): ?>
        <tr>
            <td><?= date('m/d/Y h:i A', strtotime($row['time'])) ?></td>
            <td><?= esc($row['name']) ?></td>
            <td><?= esc($row['id_num'] ?? '-') ?></td>
            <td><?= esc($row['location'] ?? '-') ?></td>
            <td><?= esc($row['description'] ?? '-') ?></td>
            <td><?= esc($row['remarks'] ?? '-') ?></td>
            <td></td>
            <td><?= esc($row['personnel_name'] ?? $row['personnel'] ?? '-') ?></td>
        </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="8">No data found</td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>

<?php
// === FOOTER FOR MPDF ===
$footerHTML = '
<table width="100%">
<tr>
    <td width="50%">Generated by: Technical Support System</td>
    <td width="50%" style="text-align:right;">Page {PAGENO} of {nb}</td>
</tr>
</table>
';
echo $footerHTML;
?>

</body>
</html>